name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    
    steps:
      - name: test
      - uses: pullreminders/label-when-approved-action@v1.0.7
        env: 
          APPROVALS: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: 承認済
      
  
